# Site settings
title: CS2030
subtitle: Theory of Computation
description: |
    Welcome to Computability theory - CS2030.
    This course covers the fundamentals of computation. We cover Finite Automata, Context Free languages, and Turing Machines.
    If time permits, we will also study more advanced problems in computational complexity theory.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tocwebsite.github.io" # the base hostname & protocol for your site
syllabus: "syllabus/svm-rmarkdown-syllabus-example.pdf"
githubdir: "tocwebsite/tocwebsite.github.io"
# Author/user information
email: kartiksrinivas007@gmail.com
# twitter_username: ste
github_username:  kartiksrinivas
# authorurl: ""
address: |
    Department of Computer Science
    Indian Institute of Technology, Hyderabad
    502-285


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
