# Site settings
title: Theory of Computation
subtitle: 
description: |
    Welcome to Computability theory - CS2030.
    This course covers the fundamentals of computation. We cover Finite Automata, Context Free languages, and Turing Machines.
    If time permits, we will also study more advanced problems in computational complexity theory.
    The course is being offered on the NPTEL Swayam portal also.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tocwebsite.github.io" # the base hostname & protocol for your site
syllabus: "syllabus/svm-rmarkdown-syllabus-example.pdf"
githubdir: "tocwebsite/tocwebsite.github.io"
nptel: "https://nptel.ac.in/courses/106106242"
youtube: "https://www.youtube.com/playlist?list=PLyqSpQzTE6M9-v4V62bCygAVYGluaijyo"
# Author/user information
email: subruk@cse.iith.ac.in
# twitter_username: ste
github_username:  tocwebsite
# authorurl: ""
people:
    - person:
            name: Subruk
            url: "https://people.iith.ac.in/subruk/"
address: |
    Department of Computer Science
    Indian Institute of Technology, Hyderabad
    Sangareddy, Telangana, 502-285


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
